name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-branch:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: check-branch-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}

  tests:
    needs: check-branch
    timeout-minutes: 10
    strategy:
      matrix:
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
        os:
          - "ubuntu"
          # - "macos"
          # - "windows"
    runs-on: ${{ matrix.os }}-latest
    concurrency:
      group: ci-tests-${{ matrix.os }}-${{ matrix.python_version }}-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: arx
          auto-update-conda: true
          conda-solver: libmamba
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          poetry check
          poetry install

      - name: Run tests
        run: makim tests.unit

      - name: Run smoke tests
        run: makim tests.smoke

  linter:
    needs: check-branch
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      group: ci-linter-docs-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: arx
          auto-update-conda: true
          conda-solver: libmamba

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Run style checks
        run: |
          pre-commit install
          makim tests.linter
